function [p1,p2,dp1,dp2,ddp1,ddp2] = autoGen_kinematics(q1,q2,dq1,dq2,ddq1,ddq2,p)
%AUTOGEN_KINEMATICS
%    [P1,P2,DP1,DP2] = AUTOGEN_KINEMATICS(Q1,Q2,DQ1,DQ2,D,L)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    07-Sep-2015 19:06:40

t2 = sin(q1);
t3 = cos(q1);

p1 = p.l1*[-sin(q1);cos(q1)];
% p1 = sqrt(sum(p1.^2, 1));

if nargout > 1
    t8 = cos(q2);
    t9 = sin(q2);
    p2 = [l.*t9-l.*t2;l.*t3-l.*t8];
%     p2 = sqrt(sum(p2.^2, 1));
end

if nargout > 2
    dp1 = [-dq1.*l.*t3;-dq1.*l.*t2];
%     dp1 = sqrt(sum(dp1.^2, 1));

end
if nargout > 3
    dp2 = [l.*dq2.*t8-dq1.*l.*t3;l.*dq2.*t9-dq1.*l.*t2];
%     dp2 = sqrt(sum(dp2.^2, 1));
    
    ddp1 = l.*[(dq1.^2).*t2-ddq1.*t3;-(dq1.^2).*t3-ddq1.*t2];
    ddp2 = l.*[(dq1.^2).*t2-ddq1.*t3-(dq2.^2).*t9+ddq2.*t8;-(dq1.^2).*t3-ddq1.*t2+(dq2.^2).*t8+ddq2.*t9];
    
%     ddp1 = sqrt(sum(ddp1.^2, 1));
%     ddp2 = sqrt(sum(ddp2.^2, 1));
    
end
