---
title: "BayesianIOC_Visualization"
author: "Pouria"
date: "1/13/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r}
# install.packages("R.matlab")
# devtools::install_github("wilkelab/ungeviz", force=TRUE)
# install.packages("ggridges")
library(R.matlab)
library(tidyr)
library(magrittr)
library(ggplot2)
library(ungeviz)
library(ggridges)
library(dplyr)
library(forcats)
library(broom)
```


## Read the matlab file for Bayesian results

```{r}

matfile = readMat('ResultsChains1500iter_20230116_BayesianIOC.mat')
matfile = readMat('ResultsChains3000iter_20230207_BayesianIOC.mat')

matfile = readMat('ResultsChains2500iter_20230222_BayesianIOC.mat')
# matfile = readMat('ResultsChains2500iter_20230222_BayesianIOC_Bases.mat')


Criteria.Names = c('1. Angular Acceleration', '2. Angular Jerk', '3. Linear Acceleration', '4. Linear Jerk',
    '5. Torque Squared', '6. Absolute Torque', '7. Torque Rate Squared', '8. Absolute Torque Rate', '9. Torque 2nd Rate Squared',
    '10. Absolute Torque 2nd Rate', '11. yGRF Rate', '12. xGRF Rate',
    '13. Positive Work Rate', '14. Absolute Work Rate', '15. Kinetic Energy', '16. Pk-to-pk Angular Momentum')



data = matfile$chain.
x_den = matfile$x.density
y_den = matfile$y.density
# W_True = c(.2, .5, .3)
We_True = matfile$W.true


tbl = data.frame()

tbl = data.frame(matrix(ncol=8,nrow=length(data), dimnames=list(NULL, c("Value", "Weight", "Weight_numeric", "Rep", "W_True", "x_density", "y_density", "Inference"))))


for (i in 0:length(data)-1) {
  
  id_obs    = mod(i, dim(data)[1]) + 1
  id_weight = i %/% (length(data)/dim(data)[2]) + 1
  id_weight = mod(i, dim(data)[2]) + 1
  id_rep    = i %/% (length(data)/dim(data)[3]) + 1
  
    tbl$Value[i+1] = data[id_obs, id_weight, id_rep]
    #tbl$Weight[i+1]= gsub(" ", "_", paste("W", id_weight))
    tbl$Weight[i+1]= Criteria.Names[id_weight]
    tbl$Weight_numeric[i+1]= id_weight
    tbl$Rep  [i+1] = gsub(" ", " ", paste("Simulation", id_rep))
    #tbl$std.err[i+1]=.15
    tbl$W_True[i+1] = We_True[id_weight]
    tbl$x_density[i+1] = x_den[id_obs, id_weight, id_rep]
    tbl$y_density[i+1] = y_den[id_obs, id_weight, id_rep]/max(y_den)
    tbl$Inference[i+1] = "Individual Costs"
}

tbl_costs <- tbl

View(tbl)

```



```{r}
matfile = readMat('ResultsChains1500iter_20230116_BayesianIOC.mat')
matfile = readMat('ResultsChains3000iter_20230207_BayesianIOC.mat')

matfile = readMat('ResultsChains2500iter_20230222_BayesianIOC.mat')
matfile = readMat('ResultsChains2500iter_20230222_BayesianIOC_Bases.mat')




data = matfile$chain.
x_den = matfile$x.density
y_den = matfile$y.density
# W_True = c(.2, .5, .3)
We_True = matfile$W.true


tbl = data.frame()

tbl = data.frame(matrix(ncol=8,nrow=length(data), dimnames=list(NULL, c("Value", "Weight", "Weight_numeric", "Rep", "W_True", "x_density", "y_density", "Inference"))))


for (i in 0:length(data)-1) {
  
  id_obs    = mod(i, dim(data)[1]) + 1
  id_weight = i %/% (length(data)/dim(data)[2]) + 1
  id_weight = mod(i, dim(data)[2]) + 1
  id_rep    = i %/% (length(data)/dim(data)[3]) + 1
  
    tbl$Value[i+1] = data[id_obs, id_weight, id_rep]
    #tbl$Weight[i+1]= gsub(" ", "_", paste("W", id_weight))
    tbl$Weight[i+1]= Criteria.Names[id_weight]
    tbl$Weight_numeric[i+1]= id_weight
    tbl$Rep  [i+1] = gsub(" ", " ", paste("Simulation", id_rep))
    #tbl$std.err[i+1]=.15
    tbl$W_True[i+1] = We_True[id_weight]
    tbl$x_density[i+1] = x_den[id_obs, id_weight, id_rep]
    tbl$y_density[i+1] = y_den[id_obs, id_weight, id_rep]/max(y_den)
    tbl$Inference[i+1] = "Cost Bases"

}

tbl_Bases <- tbl


#View(tbl)
```





## Plot the results with confidence strips

```{r}
tbl <- rbind(tbl_costs, tbl_Bases)
tbl$Inference <- factor(tbl$Inference, levels=c("Individual Costs", "Cost Bases"))
Weights = c("#F00E00" = "True Values", "#21B0D4" = "Bayesian Estimates")
True_Weights = c("#F00E00" = "True Weights")
Estimates = c("#21B0D4" = "Bayesian Estimates")



tbl1 <- tbl %>%
  group_by(Weight,Rep, Inference) %>%
  summarize(
    sd = sd(Value),
    moe = sd*1.96,
    Value = mean(Value)
  )

View(tbl1)

ggplot(tbl1, aes(x=Value, y=Weight, groups=Inference)) +
  stat_confidence_density(aes(moe = moe, groups=Inference, fill=Inference), confidence = .95, height = 0.4, position="identity") +
  xlim(0, 1) +
  # stat_confidence_density(
  #   aes(moe = moe, height = stat(density)), geom = "ridgeline",
  #   confidence = 0.95, fill = "#81A7D6", alpha = 0.5, scale = 0.08,
  #   min_height = 0.1) +
  geom_boxplot(data=tbl, aes(x = Value, y = Weight, fill=Inference),width=0.2) +
  labs(title="Cost Weight Estimates from Bayesian Inference vs. True Weights",x="Value", y = "Weight") +
  scale_y_discrete(limits = c("W_16", "W_15", "W_14", "W_13", "W_12", "W_11", "W_10", "W_9", "W_8", "W_7", "W_6", "W_5", "W_4", "W_3", "W_2", "W_1")) +
  geom_vpline(data=tbl, aes(x = W_True, group=Weight, color = "red"), size = 1.4, height = 0.4) +
  theme_bw(base_size = 16) +
  # geom_line(aes(y = x_density, x = y_density)) +
  facet_wrap(.~Rep)+
  #scale_fill_manual("Estimates", values=c(blue="#81A7D6"),
  #                   labels=c("Bayesian Estimates")) +
  scale_color_manual("Weights", values=c(red="red",blue="#81A7D6"),
                     labels=c("True Values", "Bayesian Estimates"))

# ggsave("Weight_Estimates_Strips.pdf", width = 12, height = 5)

```


## Plot the results 

```{r}
Weights = c("#F00E00" = "True Values", "#21B0D4" = "Bayesian Estimates")
True_Weights = c("#F00E00" = "True Weights")
Estimates = c("#21B0D4" = "Bayesian Estimates")



tbl1 <- tbl %>%
  group_by(Weight,Rep) %>%
  summarize(
    sd = sd(Value),
    moe = sd*1.96,
    Value = mean(Value)
  )



ggplot(tbl, aes(x = Value, y = y_density, group = Weight)) +
  geom_line() +
  xlim(0, 1)

ggplot(tbl, aes(x = x_density, y=y_density+Weight_numeric, group=Weight, fill = Weight)) +
  geom_line() +
  facet_wrap(.~Rep) +
  xlim(0, 1)

ggplot(data = tbl, 
       mapping = aes(x = Value, 
                     fill = Weight
                     )
       ) +
  geom_density(alpha = 0.5) +
  facet_wrap(.~Rep) +
  xlim(0,1)
  

ggplot(tbl, aes(x = Value, y = Weight, fill = 0.5 - abs(0.5 - stat(ecdf)))) +
  xlim(0,1) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE, alpha=.1) +
  scale_fill_viridis_c(name = "Tail probability", direction = -1) +
  facet_wrap(.~Rep) +
  geom_vpline(tbl, aes(x = W_True, group=Weight, color = "red"), size = 1.2, height = 0.6) +
  theme_bw(base_size = 16) 
  





ggplot(tbl, aes(x = Value, y = Weight, fill = abs(stat(x)))) +
  stat_density_ridges(scale = 1, geom = "density_ridges_gradient", calc_ecdf = TRUE, alpha=.1, na.rm=T) +
  geom_vpline(aes(x = W_True, group=Weight), color = "red", size = 1.2, height = 0.6, show = F) + 

  scale_fill_viridis_c(name = "Tail probability", direction = 1) +
  xlim(0,1) +
  facet_wrap(.~Rep)+
  theme_bw(base_size = 16) +
  # geom_line(aes(y = x_density, x = y_density)) +
  scale_color_manual("Weights", values=c(red="red",blue="#21B0D4"),
                     labels=c("True Values", "Bayesian Estimates"))




ggplot(tbl, aes(x = Value, y = Weight, fill = factor(stat(quantile)))) +
stat_density_ridges(
    geom = "density_ridges_gradient",
    calc_ecdf = TRUE,
    quantiles = c(0.025, 0.975)
  ) +
  geom_vpline(aes(x = W_True, group=Weight), color = "red", size = 1.2, height = 0.6, show = F) + 
  scale_fill_manual(
    name = "Probability", values = c("#FF0000A0", "#A0A0A0A0", "#0000FFA0"),
    labels = c("(0, 0.025]", "(0.025, 0.975]", "(0.975, 1]")
  ) 
      geom_vpline(aes(x = W_True, group=Weight, color = "red"), size = 1.2, height = 0.6, show = F) +
  facet_wrap(.~Rep)
  theme_bw(base_size = 16) 
  # geom_line(aes(y = x_density, x = y_density)) +
  scale_color_manual("Weights", values=c(red="red",blue="#21B0D4"),
                     labels=c("True Values", "Bayesian Estimates"))




  
stat_confidence_density(
    aes(moe = moe, height = stat(density)), geom = "ridgeline",
    confidence = 0.95, fill = "#81A7D6", alpha = 0.5, scale = 0.08,
    min_height = 0.1
  ) +
  geom_boxplot(data=tbl, aes(x = Value, y = Weight),width=0.2, fill="white")+
  labs(title="Cost Weight Estimates from Bayesian Inference vs. True Weights",x="Value", y = "Weight") +
  scale_y_discrete(limits = c("W_3", "W_2", "W_1")) +
  geom_vpline(data=tbl, aes(x = W_True, group=Weight, color = "red"), size = 1.2, height = 0.6, show = F) +
  theme_bw(base_size = 16) +
  # geom_line(aes(y = x_density, x = y_density)) +
  facet_wrap(.~Rep)
  scale_color_manual("Weights", values=c(red="red",blue="#81A7D6"),
                     labels=c("True Values", "Bayesian Estimates"))

ggsave("Weight_Estimates.pdf", width = 12, height = 7)

```


## ECDF (Cumulative Distribution Function)

Here we plot the distribution of the posteriors obtained for the cost weight estimates. The results are not binned and the distribution is showcasing all observations.


```{r}

ggplot(tbl, aes(x = Value, y = Weight, fill = stat(quantile))) +
  stat_density_ridges(quantile_lines = TRUE,
                      calc_ecdf = TRUE,
                      geom = "density_ridges_gradient",
                      quantiles = c(0.05, 0.95)) +
  scale_fill_manual(name = "Prob.", values = c("#C1FFF2", "white", "#A9E0E6"),
                    labels = c("(0, 2.5%]", "(2.5%, 97.5%]", "(97.5%, 1]")) +
  scale_color_manual(name = "", values = c( "red"),
                    labels = c("True Weights")) +
  #geom_point(aes(x = W_True, y = Weight, color = "red"), data = tbl, inherit.aes = F)
  geom_vpline(aes(x = W_True, y=Weight, color = "red"), data=tbl, size = 1.2, height = 0.6, show = F, inherit.aes = F) +
  facet_wrap(.~Rep) +
  theme_bw(base_size = 16) 
  # geom_line(aes(y = x_density, x = y_density)) +
  # scale_color_manual("Weights", values=c(red="red",blue="#000000"),
  #                   labels=c("True Values", "Posterior Density")) +
    scale_y_discrete(limits = c("W_3", "W_2", "W_1")) +
  xlim(0,1)

ggplot(tbl, aes(Value, y = Weight,
               fill = 0.5 - abs(0.5 - stat(ecdf)))) +
  stat_density_ridges(scale = 1.5, geom = "density_ridges_gradient", calc_ecdf = TRUE, alpha = .9) +
  scale_fill_gradient(low = "white", high = "#58A1D6",
                      name = "Tail probability") +
  #geom_point(aes(x = W_True, y = Weight, color = "red"), data = tbl, inherit.aes = F) +

  geom_vpline(data=tbl, aes(x = W_True, y=Weight, color = "red"), size = 1.1, height = 0.2, show = F, inherit.aes = F) +
  facet_wrap(.~Rep) +
  theme_bw(base_size = 16) +
  # geom_line(aes(y = x_density, x = y_density)) +
  # scale_color_manual("Weights", values=c(red="red",blue="#000000"),
  #                    labels=c("True Values", "Posterior Density")) +
  #scale_y_discrete(limits = c("W_5", "W_4","W_3", "W_2", "W_1")) +
  xlim(0,1)
ggsave("Weight_Estimates_Posterior.pdf", width = 12, height = 5)

```



## Both Individual Costs and Cost Bases

```{r}

ggplot(tbl, aes(x = Value, y = Weight, fill = stat(quantile), groups=Inference)) +
  stat_density_ridges(quantile_lines = TRUE,
                      calc_ecdf = TRUE,
                      geom = "density_ridges_gradient",
                      quantiles = c(0.025, 0.975)) +
  #scale_fill_manual(name = "Prob.", values = c("#C1FFF2", "white", "#A9E0E6"),
  #                  labels = c("(0, 2.5%]", "(2.5%, 97.5%]", "(97.5%, 1]")) +
  scale_color_manual(name = "", values = c( "red", "green"),
                    labels = c("True Weights")) +
  #geom_point(aes(x = W_True, y = Weight, color = "red"), data = tbl, inherit.aes = F)
  geom_vpline(aes(x = W_True, y=Weight, color = "red"), data=tbl, size = 1.2, height = 0.6, show = F, inherit.aes = F) +
  facet_wrap(.~Rep) +
  theme_bw(base_size = 16) 
  # geom_line(aes(y = x_density, x = y_density)) +
  # scale_color_manual("Weights", values=c(red="red",blue="#000000"),
  #                   labels=c("True Values", "Posterior Density")) +
    scale_y_discrete(limits = c("W_3", "W_2", "W_1")) +
  xlim(0,1)


```




```{r}
ggplot(tbl, aes(Value, y = Weight,
               fill = 0.5 - abs(0.5 - stat(ecdf)))) +
  stat_density_ridges(scale = 1.5, geom = "density_ridges_gradient", calc_ecdf = TRUE, alpha = .9) +
  scale_fill_gradient(low = "white", high = "#58A1D6",
                      name = "Tail probability") +
  #geom_point(aes(x = W_True, y = Weight, color = "red"), data = tbl, inherit.aes = F) +

  geom_vpline(data=tbl, aes(x = W_True, y=Weight, color = "red"), size = 1.1, height = 0.2, show = F, inherit.aes = F) +
  facet_wrap(.~Rep) +
  theme_bw(base_size = 16) +
  # geom_line(aes(y = x_density, x = y_density)) +
  # scale_color_manual("Weights", values=c(red="red",blue="#000000"),
  #                    labels=c("True Values", "Posterior Density")) +
  #scale_y_discrete(limits = c("W_5", "W_4","W_3", "W_2", "W_1")) +
  xlim(0,1)
ggsave("Weight_Estimates_Posterior.pdf", width = 12, height = 5)

```




```{r}
 ggplot(tbl, aes(x = Value, y = Weight, color= Inference,  fill = Inference)) +
  geom_density_ridges(
    jittered_points = F, scale = 1.5, rel_min_height = .1,
    point_shape = "|", point_size = 3, size = .3,
    position = position_points_jitter(height = 0)
  ) +
  #scale_fill_manual(name = "Prob.", values = c("#C1FFF2", "white", "#A9E0E6"),
  #                  labels = c("(0, 2.5%]", "(2.5%, 97.5%]", "(97.5%, 1]")) +
  #scale_color_manual(name = "", values = c( "red"),
  #                  labels = c("True Weights")) +
  scale_fill_manual(values = c("#0072B250","#D55E0050",  "red"), name= "Inferred from") +
  scale_color_manual(values = c("#B55E00", "#1072B2", "red"), name="", labels= c("", "", "True Weights")) +
  scale_discrete_manual("point_color", values = c("#D55E00", "#0072B2", "red"), name = "name") + 
  geom_vpline(data=tbl, aes(x = W_True, y=Weight, color = True_Weights), size = 1.1, height = 0.2, show = T, inherit.aes = T) +
  scale_y_discrete(expand = c(0, 0), limits = rev(Criteria.Names), name = "Cost") +
  scale_x_continuous(expand = c(0, 0), name = "Weighting") +
  facet_wrap(.~Rep) +
  #coord_cartesian(clip = "off") +
  #guides(fill = guide_legend(
  #  override.aes = list(
  #    fill = c("#D55E00A0", "#0072B2A0"),
  #    color = NA, point_color = NA)
  #  )
  #) +
  ggtitle("Locomotor Cost Weights Posteriors Inferred from Bayesian Inference") +
  theme_ridges(center=T)
ggsave("Weight_Estimates_Posterior.pdf", width = 12, height = 5)

```










```{r}
matfile = readMat('Synthetic_Timeseries_Bases_R.mat')
# matfile = readMat('ResultsChains2500iter_20230222_BayesianIOC_Bases.mat')


Time = matfile$Time
Torso = matfile$Torso
Femur.Stance = matfile$Femur.Stance
Femur.Swing = matfile$Femur.Swing
Tibia.Stance = matfile$Tibia.Stance
Tibia.Swing = matfile$Tibia.Swing
Speed = matfile$Speed
Cost  = matfile$Cost

df <- data.frame(Time, Torso=Torso, Femur.Swing = Femur.Swing, Femur.Stance=Femur.Stance, Tibia.Swing=Tibia.Swing, Tibia.Stance=Tibia.Stance, Speed=Speed, Cost=Cost)

View(df)
df_long <- df %>% pivot_longer(cols=2:6, names_to = "Variable", values_to="Limb_Angles")
  
df_long <- df_long %>%
  filter(Cost==1)
  
View(df_long)

#Femur.Stance.Traj <- df_long %>%
#  filter(Variable=="Femur.Stance" & Speed == c(.4,.7))

#View(Femur.Stance.Traj)

```

```{r}
ggplot(df_long, aes(x=Time, y=Limb_Angles, group=Speed)) +
  geom_line(aes(x=Time, y=Limb_Angles, col=Speed), size=.9) +
  facet_grid(Variable~.) +
  #scale_fill_manual(values = c("#0072B250","#D55E0050",  "red"), name= "Inferred from") +
  #scale_color_manual(values = c("#B55E00", "#1072B2", "red"), name="", labels= c("", "", "True Weights")) +
  #scale_discrete_manual("point_color", values = c("#D55E00", "#0072B2", "red"), name = "name") + 
  scale_y_discrete(expand = c(0, 0), limits=c(-.25, 0, .25), name = "Limb Angles (rad)") +
  scale_x_continuous(expand = c(0, 0), name = "Time (s)") +
  #coord_cartesian(clip = "off") +
  #guides(fill = guide_legend(
  #  override.aes = list(
  #    fill = c("#D55E00A0", "#0072B2A0"),
  #    color = NA, point_color = NA)
  #  )
  #) +
  ggtitle("Synthetic Data: Predicted Locomotor Patterns from Forward Simulations of Gait") +
  theme_ridges(center=T)
ggsave("Synthetic_Patterns.pdf", width = 9.5, height = 8)
```







```{r}
matfile = readMat('Trajectories_Bayesian_Bases.mat')
# matfile = readMat('ResultsChains2500iter_20230222_BayesianIOC_Bases.mat')


Time = matfile$Time
Torso = matfile$Torso
Femur.Stance = matfile$Femur.Stance
Femur.Swing = matfile$Femur.Swing
Tibia.Stance = matfile$Tibia.Stance
Tibia.Swing = matfile$Tibia.Swing
Speed = matfile$Speed
Cost  = matfile$Cost
Simulation = paste('Simulation', matfile$Simulation)
Obs = matfile$Obs
Error=paste('RMS =',matfile$Error)

df <- data.frame(Time, Torso=Torso, Femur.Swing = Femur.Swing, Femur.Stance=Femur.Stance, Tibia.Swing=Tibia.Swing, Tibia.Stance=Tibia.Stance, Speed=Speed, Cost=Cost, Simulation=Simulation, Obs=Obs, RMS=Error)

df_Traj <- df %>% pivot_longer(cols=2:6, names_to = "Variable", values_to="Limb_Angles")
View(df_Traj)

df_Traj <- df_Traj %>%
  filter(Cost==1)
  
# View(df_long)

#Femur.Stance.Traj <- df_long %>%
#  filter(Variable=="Femur.Stance" & Speed == c(.4,.7))

#View(Femur.Stance.Traj)

```


```{r}
ggplot(df_Traj,aes(x=Time, y=Limb_Angles, group=Speed, col=Speed)) +
#  geom_line(aes(x=Time, y=Limb_Angles, col=Speed), size=.9) +
  geom_smooth(show.legend = T) +
  geom_line(data=df_long,aes(x=Time, y=Limb_Angles, group=Speed), col="black", size=.3, linetype=2, show.legend = T) +
  facet_grid(Variable~Simulation+RMS) +
  #scale_fill_manual(values = c("#0072B250","#D55E0050",  "red"), name= "Inferred from") +
  #scale_color_manual(values = c("#B55E00", "#1072B2", "red"), name="", labels= c("", "", "True Weights")) +
  scale_discrete_manual("point_color", values = c("red"), name = "name") + 
  scale_y_discrete(expand = c(0, 0), limits=c(-.25, 0, .25), name = "Limb Angles (rad)") +
  scale_x_continuous(expand = c(0, 0), name = "Time (s)") +
  #coord_cartesian(clip = "off") +
  #guides(fill = guide_legend(
  #  override.aes = list(
  #    fill = c("#D55E00A0", "#0072B2A0"),
  #    color = NA, point_color = NA)
  #  )
  #) +
  ggtitle("Feature-reduced Bayesian Inference") +
  #ggtitle("Naïve Bayesian Inference") +
  #ggtitle("Locomotor Patterns Recovered by Naïve Bayesian Inference") +
  theme_ridges(center=T)
ggsave("Bayesian_Results_Trajectories_Naive.pdf", width = 7, height = 8)
ggsave("Bayesian_Results_Trajectories_Feature-reduced.pdf", width = 7, height = 8)

```





```{r}
ggplot(cacao_means, aes(x = estimate, y = location)) +
  stat_confidence_density(aes(moe = std.error), confidence = 0.68, fill = "#81A7D6", height = 0.7) +
  geom_errorbarh(aes(xmin = estimate - std.error, xmax = estimate + std.error), height = 0.3) +
  geom_vpline(aes(x = estimate), size = 1.5, height = 0.7, color = "#D55E00") +
  xlim(2.8, 3.6) + 
  theme_minimal()
```

